apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: cert-manager
  url: quay.io/jetstack/charts
  type: helm
  enableOCI: "true"