apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  type: kv-v2
  mount: secret
  path: harbor/admin
  refreshAfter: 1h
  vaultAuthRef: harbor-vault-auth
  destination:
    name: harbor-admin-secret
    create: true
    transformation:
      templates:
        HARBOR_ADMIN_PASSWORD:
          text: |
            {{- get .Secrets "password"}}