apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata: 
  name: zot-auth-secret
  namespace: zot
spec:
  type: kv-v2
  mount: secret
  path: zot/auth
  refreshAfter: 1h
  vaultAuthRef: zot-vault-auth
  destination:
    name: zot-secret
    create: true 