apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-platform-charts
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: argocd/repos/platform-charts
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
  destination:
    name: argocd-repo-platform-charts
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-platform-components
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: argocd/repos/platform-components
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
  destination:
    name: argocd-repo-platform-components
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-platform-deploy
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: argocd/repos/platform-deploy 
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
  destination: 
    name: argocd-repo-platform-deploy
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-platform-infra
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: argocd/repos/platform-infra
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
  destination:
    name: argocd-repo-platform-infra
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-ml-classifier
  namespace: argocd
spec:
  type: kv-v2
  mount: secret
  path: argocd/repos/ml-classifier
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
  destination: 
    name: argocd-repo-ml-classifier
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository