apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    # Source 1: Official helm chart - OCI
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/services/cert-manager-helm/values.yaml
    - repoURL: git@github.com:somepulp/platform-components
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true