apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # Source 1: official helm chart - OCI
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.8.1
    - repoURL: git@github.com:somepulp/platform-components
      targetRevision: HEAD
      path: services/envoy-gateway-system
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true