apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $values/services/harbor-helm/values.yaml
    - repoURL: git@github.com:somepulp/platform-components
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:somepulp/platform-components
      targetRevision: HEAD
      path: services/harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
