apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-deploy-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: git@github.com:somepulp/platform-deploy
    targetRevision: cluster/local
    path: .
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true