apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 1.4.0
      helm:
        valueFiles:
          - $values/services/vault-secrets-operator-helm/values.yaml
    - repoURL: git@github.com:somepulp/platform-components
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true